steps:
  # Step 1: Install dependencies
  - name: "node:14"
    entrypoint: "npm"
    args: ["install"]

  # # Step 2: Run unit tests
  # - name: 'node:14'
  #   entrypoint: 'npm'
  #   args: ['test']

  # # Step 3: Lint the code
  # - name: "node:14"
  #   entrypoint: "npm"
  #   args: ["run", "lint"]

  # # Step 4: Build the Docker image
  # - name: "gcr.io/cloud-builders/docker"
  #   args: ["build", "-t", "gcr.io/$PROJECT_ID/app", "."]

  # # Step 5: Push the Docker image to Google Container Registry (GCR)
  # - name: "gcr.io/cloud-builders/docker"
  #   args: ["push", "gcr.io/$PROJECT_ID/app"]

  # Step 6: Deploy the service to Cloud Run
  - name: "gcr.io/cloud-builders/gcloud"
    args:
      [
        "run",
        "deploy",
        "my-service",
        "--image",
        "gcr.io/$PROJECT_ID/app",
        "--platform",
        "managed",
        "--region",
        "us-central1",
      ]

# Optional: Define environment variables for your build
substitutions:
  _REGION: "us-central1"
  _SERVICE: "my-service"

# Timeout for the build process
timeout: 900s
