steps:
  # Step 1: Install dependencies
  - name: "node:16"
    entrypoint: "npm"
    args: ["install"]
  
  -name: "node:16"
    args: ["run", "create-env"]
    env:
    - 'PORT=${_PORT}'
    - 'JWT_SECRET_KEY'=${_JWT_SECRET_KEY}
    - 'TOKEN_HEADER_KEY'=${_TOKEN_HEADER_KEY}

  # # Step 2: Run tests (optional, remove if not needed)
  # - name: "node:16"
  #   entrypoint: "npm"
  #   args: ["test"]

  # Step 3: Deploy to Cloud Run using Cloud Buildpacks
  - name: "gcr.io/cloud-builders/gcloud"
    args:
      - "run"
      - "deploy"
      - "nodejs-app"
      - "--source"
      - "."
      - "--platform"
      - "managed"
      - "--region"
      - "asia-south1"
      - "--allow-unauthenticated"
      - "--project"
      - "ecstatic-valve-441717-n8"

# Enable Cloud Logging only for the build logs
options:
  logging: CLOUD_LOGGING_ONLY

# Set the build timeout (optional, default is 10 minutes)
timeout: 900s
